### ISSUE TITLE
Overlay causing game crash with new AMD Drivers

### ISSUE THREAD

**Issue by Escort95** [Koenvh1/ets2-local-radio#105]
My graphics AMD RX580. On drivers 19.12.1+ and 20.5.1 the overlay keeps crashing game when I change the station. 
On driver 19.8.2 it's working fine

**Comment by Koenvh1** [comment]
I don't have a working computer with AMD GPU here at the moment, so if anyone else can confirm that this is happening for them now too (and it worked before), that'd be great. Extra great if you could fix it too, of course. You can turn off the overlay in the `settings.json` file.

**Comment by rafdes15** [comment]
My game is crashing too. I'm using AMD  20.4.2. I don't know if it is the overlay, because I tried turning off. Not sure I did it right. Do I change the "true" part to "false"? or just delete the whole line?

**Comment by Koenvh1** [comment]
@Escort95 @rafdes15 Can you share your Error log.txt file (in the install directory)?
It should be just setting it to false, however, I did find an issue which might cause it to crash even with the overlay disabled. I will fix that in a bit, but I would prefer fixing the actual problem (and making the overlay work) instead of just having a workaround.

**Comment by Escort95** [comment]
I have only this:
01:42:03: Device found: Logitech G HUB G29 Driving Force Racing Wheel USB
01:42:03: Device found: Logitech G HUB G29 Driving Force Racing Wheel USB

**Comment by Escort95** [comment]
For me all AMD Drivers causes overlay to crash game only older than 19.8.2 works great.

**Comment by rafdes15** [comment]
Here's my error log:

10:11:58 PM: Device found: Thrustmaster T300RS Racing Wheel
10:11:58 PM: Device found: Thrustmaster T300RS Racing Wheel
10:12:02 PM: Not found: C:\Program Files (x86)\ETS2 Local Radio\web\custom.js
10:12:20 PM: Not found: C:\Program Files (x86)\ETS2 Local Radio\web\custom.js
10:12:43 PM: Process attached: eurotrucks2 (Width: 0; Height: 0)
10:12:44 PM: Not found: C:\Program Files (x86)\ETS2 Local Radio\web\custom.js
10:26:04 PM: Not found: C:\Program Files (x86)\ETS2 Local Radio\web\custom.js
10:28:41 PM: Process attached: eurotrucks2 (Width: 0; Height: 0)
10:28:41 PM: No capture process bound
10:29:46 PM: Process attached: eurotrucks2 (Width: 0; Height: 0)
10:30:28 PM: Process attached: eurotrucks2 (Width: 0; Height: 0)
10:30:28 PM: No capture process bound
10:30:52 PM: Process attached: eurotrucks2 (Width: 3440; Height: 1440)
10:34:21 PM: Process attached: eurotrucks2 (Width: 3440; Height: 1440)
10:34:21 PM: No capture process bound
10:49:50 PM: Not found: C:\Program Files (x86)\ETS2 Local Radio\web\custom.js
10:50:13 PM: Process attached: eurotrucks2 (Width: 3440; Height: 1440)
10:51:36 PM: Process attached: eurotrucks2 (Width: 3440; Height: 1440)
10:51:36 PM: No capture process bound
11:32:37 PM: System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Net.UnsafeNclNativeMethods.HttpApi.HttpReceiveHttpRequest(CriticalHandle requestQueueHandle, UInt64 requestId, UInt32 flags, HTTP_REQUEST* pRequestBuffer, UInt32 requestBufferLength, UInt32* pBytesReturned, NativeOverlapped* pOverlapped)
   at System.Net.HttpListener.GetContext()
   at ETS2_Local_Radio_server.SimpleHTTPServer.Listen()
11:32:37 PM: System.Threading.ThreadAbortException: Thread was being aborted.
   at ETS2_Local_Radio_server.SimpleHTTPServer.Listen()

**Comment by Koenvh1** [comment]
Great. Then it is not just the application that crashes, but it does not even get any information why it crashed. If you set `overlay` to `false`, and then replace `ETS2 Local Radio server.exe` with this version: 
[ETS2 Local Radio server.zip](https://github.com/Koenvh1/ets2-local-radio/files/4810122/ETS2.Local.Radio.server.zip), does it work then?

**Comment by Koenvh1** [comment]
Also, check whether the Windows Event Viewer shows some more information about the crash. It should be under: Right-click the start button > Event Viewer > Windows events > Application.

**Comment by rafdes15** [comment]
Will try the other things soon but here's window event log for ets2

Application Error 1000
Faulting application name: eurotrucks2.exe, version: 1.37.1.74, time stamp: 0x5ed7cdd2
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffcd8840000
Faulting process id: 0x622c
Faulting application start time: 0x01d6478fd49eca2b
Faulting application path: D:\SteamLibrary\steamapps\common\Euro Truck Simulator 2\bin\win_x64\eurotrucks2.exe
Faulting module path: unknown
Report Id: dad8bae6-46db-4736-9692-fb4978a2f9c5
Faulting package full name: 
Faulting package-relative application ID:

**Comment by rafdes15** [comment]
also sorry @Escort95 didn't mean to hijack your thread

**Comment by rafdes15** [comment]
Here's the other error

Event 1026 .NET Runtime
Application: eurotrucks2.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFCD8840000
Stack:

**Comment by rafdes15** [comment]
OK, so I set overlay to false and replaced the .exe and that seems to have worked. Note I did turn off the overlay yesterday and it still crashed, so the new .exe seems to be the solution, at least for me. Thanks @Koenvh1

**Comment by Escort95** [comment]
I will try that also later tomorrow

**Comment by Koenvh1** [comment]
@Escort95 Any luck? I'll probably publish an update if that resolves things. Then I hope AMD resolves the bug in the next driver version.

**Comment by Escort95** [comment]
It worked with overlay=true and alternative telemetry plugin but I have FPS drop inside the truck with it. 
I installed normal telemetry plugin and set overlay=false and everything working but overlay don't work.
When I set overlay=true the game starting crashing again

**Comment by Koenvh1** [comment]
Well, setting the overlay to false turns off the overlay, that is all it does. 
Now, the other telemetry plugin does not do anything special, it is the same version compiled with VC++ 2015 instead of VC++ 2012. If that makes it work, then I suspect you have a different problem that is not related to the overlay at all.

**Comment by Escort95** [comment]
I installed another telemetry plugin (i don't know which, i have it copied in desktop) and set overlay to true and It's working again.

**Comment by Koenvh1** [comment]
Like I said, I suspect you have a different problem that is not related to the overlay at all.

**Comment by Escort95** [comment]
Maybe, but i'm happy that it's working again :) 
My ETS2 minimalized is taking 100% graphics card usage so I have many others problems with this game

**Comment by Escort95** [comment]
That .exe you send also helped me and make my local radio working again so thanks for help

**Comment by VenisonSneers** [comment]
> I installed another telemetry plugin (i don't know which, i have it copied in desktop) and set overlay to true and It's working again.

Hi, please could you let me know which telemetry plugin  you used or where you got it from that allowed you to also be able to use the overlay at the same time.
I have the same problem as you where I can get the radio mod to work but only with the overlay set to false and with the server zip file Koenvh1 provided further up. If the overlay is set to true (even with the new server zip), the game still crashes in VR.
I am on a HTC Vive with an RTX 2070 Super so the problem even occurs with Nvidia cards/drivers.
