### ISSUE TITLE
Overlay not working anymore

### ISSUE THREAD

**Issue by pcvdbroek** [Koenvh1/ets2-local-radio#125]
The first time i installed and used this, the overlay was working fine. After that it hasn't worked since. I uninstalled and installed again, tried some settings, nothing works to get it back...
I do run the program as adminstrator and installed the plugin. I do get the following error:

System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: The process cannot access the file 'C:\Program Files (x86)\ETS2 Local Radio\tmp.png' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at ETS2_Local_Radio_server.Station.SetStation(String name, String signal, String logoPath)

**Comment by Koenvh1** [comment]
Are you running ETS2/ATS in DirectX mode? It also stops working if you restart ETS2/ATS, because the overlay is still bound to the old window.

**Comment by pcvdbroek** [comment]
I have tried in DX mode and starting it "normal" (without selecting any mode), makes no difference. What would be the proper order to run things, first ETS2 and then local radio, or the other way around? Does the website need to be open in the background?

**Comment by Koenvh1** [comment]
Generally first open Local Radio, then the webpage, then the game. The web page needs to be open as it does most of the heavy lifting, although you are free to choose on which device you open it (generally the same computer, but some use their tablet or phone).

**Comment by pcvdbroek** [comment]
Ok, i was thinking about the error i got, so i deleted the tmp.png file from the local radio folder, and now the overlay works again! Apparently it was locked by some process (even after reboot). Maybe this could help other people too if they have this problem ;)
I am happy now, since i really like the app (and the idea behind it)...
