### ISSUE TITLE
v1.9.0: can't get coordinates in browser

### ISSUE THREAD

**Issue by markuskolic** [Koenvh1/ets2-local-radio#13]
On upgrading to 1.9.0, the server application displays the game state and coordinates correctly, but on opening the client in the browser, I just see the "Waiting for your in-game coordinates..." message and hear static. Reverting to 1.8.0 resolves the issue.

This message appears in the error log:
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Net.UnsafeNclNativeMethods.HttpApi.HttpReceiveHttpRequest(CriticalHandle requestQueueHandle, UInt64 requestId, UInt32 flags, HTTP_REQUEST* pRequestBuffer, UInt32 requestBufferLength, UInt32* pBytesReturned, NativeOverlapped* pOverlapped)
   at System.Net.HttpListener.GetContext()
   at ETS2_Local_Radio_server.SimpleHTTPServer.Listen()
System.Threading.ThreadAbortException: Thread was being aborted.
   at ETS2_Local_Radio_server.SimpleHTTPServer.Listen()

OS: Windows 10 64-bit
Affected: ETS2 1.26.6s, ATS 1.5.3s

**Comment by Koenvh1** [comment]
I just tested it myself with a fresh copy, and I face no such issue. Could you try reloading the page? It may still have an invalid cached version. 
If you press F12 in your browser, and go to the "Console" tab, does it show any errors?

**Comment by markuskolic** [comment]
@Koenvh1 you're right, it was just the browser cache -- hard refresh fixed it. Thanks! Closing issue.
