### ISSUE TITLE
.NET Framework exception (SlimDX.dll)

### ISSUE THREAD

**Issue by 1rfsNet** [Koenvh1/ets2-local-radio#155]
Hello, I have the following problem, after starting the tool. I used the latest installer exe and already checked all other issues about this error but unfortunately nothing helped. Even tried to reinstall Microsoft Visual C++ 2010 Redistributable Package (x86) (btw: the link from faq to microsoft download is down) but it didn't help.

![image](https://user-images.githubusercontent.com/48516961/130620202-67d591f6-80ed-48c6-9d12-832d97f16524.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.BadImageFormatException: Could not load file or assembly 'SlimDX.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)
File name: 'SlimDX.dll'
   at ETS2_Local_Radio_server.Main.Main_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)




************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ETS2 Local Radio server
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/ETS2%20Local%20Radio/ETS2%20Local%20Radio%20server.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by Koenvh1** [comment]
I am aware the link leads to a 404 - I will fix that at some point, although the nice side-effect is that when people say "I have tried that" without mentioning that fact, I am pretty sure that they have not, so part of me wants to keep it in. You are so far the first to mention it.

Anyway, you can download it here: https://www.majorgeeks.com/mg/get/microsoft_visual_c_2010_redistributable,1.html
You might also want to check whether this works: https://www.microsoft.com/en-gb/download/details.aspx?id=17851 and https://www.microsoft.com/en-us/download/details.aspx?id=35 

This is the full list of dependencies it loads, you are probably missing one of them, but I would not know which one:
![image](https://user-images.githubusercontent.com/5168825/130623158-6627ef81-9f16-4d04-bbb3-e4cc21c1ea4f.png)

**Comment by 1rfsNet** [comment]
Any other idea? already searched for the visual c installer on my own and already had it installed. So I tried to reinstall but it is still not working (of course I rebooted).

I now checked every single file and I have them all on my computer. None is missing...

**Comment by Koenvh1** [comment]
Also try the other two links to the .NET Framework and DirectX. I believe it might be caused by the latter.

**Comment by 1rfsNet** [comment]
ups forgot to mention: tried both installers. no luck :(

**Comment by Koenvh1** [comment]
Try downloading https://github.com/lucasg/Dependencies and opening the SlimDX.dll in it. You should see a similar window as the one above, including some icons where it says that a dependency is missing. Just Google the name and it should lead you to the dependency they belong to.

**Comment by 1rfsNet** [comment]
Strange, says msvcr100.dll is missing but is in C:\Windows\SysWOW64

![image](https://user-images.githubusercontent.com/48516961/130639155-a49397bf-8734-4f4b-94e7-b4396a06ee16.png)

**Comment by Koenvh1** [comment]
msvcr100 - MicroSoft Visual C(++) Runtime, version 10.0 (hence 100), which is the one linked in the FAQ.

I'd try to remove it from your computer (should be listed under "Apps") and reinstall it:
https://www.microsoft.com/en-us/download/details.aspx?id=26999
(just to be sure, try both the x86 and x64 versions, although only x86 should be necessary)
