### ISSUE TITLE
Can't use the app

### ISSUE THREAD

**Issue by Julmath** [Koenvh1/ets2-local-radio#29]
Hey,

Since yesterday I'm actually unable to use your app.
I'm getting an error, you'll be able to find a screenshot below.
Do you know how can I fix this?

![capture2](https://user-images.githubusercontent.com/27033603/27995619-03dbaa42-64d2-11e7-97f2-bf418a03e4ea.JPG)

**Comment by Koenvh1** [comment]
Could you send the content of error message? (Click the Details 🔽 button). And could you also send me your `settings.json` and `Error log.txt` file in your installation directory? 

I'd like to find out the actual issue, but if you want a quick fix, just remove the `settings.json` file from your installation directory and start ETS2 Local Radio again.

**Comment by Julmath** [comment]
Yeah, sure.

> See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

> ************** Exception Text **************
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 1, position 699.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at ETS2_Local_Radio_server.Settings.Load()
   at ETS2_Local_Radio_server.Main.Main_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


> ************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2098.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
> ETS2 Local Radio server
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/ETS2%20Local%20Radio/ETS2%20Local%20Radio%20server.exe
----------------------------------------
> System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2094.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
> System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2093.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
> System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
> System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
> System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2098.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
> System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
> SlimDX
    Assembly Version: 4.0.13.43
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files%20(x86)/ETS2%20Local%20Radio/SlimDX.DLL
----------------------------------------
> Ets2SdkClient
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/ETS2%20Local%20Radio/Ets2SdkClient.DLL
----------------------------------------
> Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.1.19813
    CodeBase: file:///C:/Program%20Files%20(x86)/ETS2%20Local%20Radio/Newtonsoft.Json.DLL
----------------------------------------
> Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------

> ************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

> For example:

> <configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

> When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

[settings.json](https://mega.nz/#!cQIlwK4a!RoveCg_ATdUa4waXaou9IyOF1I_k8lsENCxvOwEZcqU)
[Error log.txt](https://github.com/Koenvh1/ets2-local-radio/files/1133913/Error.log.txt)

**Comment by Koenvh1** [comment]
Yup, your settings.json file seems to be corrupted. It normally looks something like this:
```json
{
  "language": "en-US",
  "port": 8330,
  "overlay": true,
  "controller": "Logitech G27 Racing Wheel USB",
  "keys": {
    "previous": "PageUp",
    "next": "Next",
    "stop": "End",
    "volumeUp": "Oemplus",
    "volumeDown": "OemMinus",
    "makeFavourite": "",
    "goToFavourite": ""
  },
  "buttons": {
    "previous": "22",
    "next": "21",
    "stop": "129",
    "volumeUp": "",
    "volumeDown": "",
    "makeFavourite": "131",
    "goToFavourite": ""
  },
  "folders": {
    "ets2": "B:\\Apps\\Steam\\SteamApps\\common\\Euro Truck Simulator 2",
    "ats": "B:\\Apps\\Steam\\SteamApps\\common\\American Truck Simulator"
  }
}
```

yours looks like:

```json
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
```
(That's not empty, but NUL characters)

Why and how? No idea, probably some issue when writing the file. Will look into it, but the solution for now is just to delete the `settings.json` file. It'll automatically generate a new one next time you start up ETS2 Local Radio server.
