### ISSUE TITLE
Caught in loop

### ISSUE THREAD

**Issue by JethroE7** [Koenvh1/ets2-local-radio#59]
Hi, 
The radio seems to work, and I can switch stations and worked fine for about 20 minutes, but is now looping the first 3 seconds of the radio station endlessly.  
Any ideas what could be wrong?

**Comment by JethroE7** [comment]
Not found: C:\Program Files (x86)\ETS2 Local Radio\web\lib\css\light\bootstrap.css
Not found: C:\Program Files (x86)\ETS2 Local Radio\web\stations\stations-custom.js
Not found: C:\Program Files (x86)\ETS2 Local Radio\web\lib\css\light\bootstrap.css
Not found: C:\Program Files (x86)\ETS2 Local Radio\web\stations\stations-custom.js
Not found: C:\Program Files (x86)\ETS2 Local Radio\web\lib\css\light\bootstrap.css
Not found: C:\Program Files (x86)\ETS2 Local Radio\web\stations\stations-custom.js
System.Net.HttpListenerException (0x80004005): The specified network name is no longer available
   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at ETS2_Local_Radio_server.SimpleHTTPServer.Process(HttpListenerContext context)

**Comment by Koenvh1** [comment]
Try refreshing the page, sometimes the stream gets stuck, because of some unknown HLS playback issue. Problem is that I can't reliably reproduce it, and hence have not been able to fix it.
