### ISSUE TITLE
Visual C++2015-2019 Redistributable  problem

### ISSUE THREAD

**Issue by Rayzer78** [Koenvh1/ets2-local-radio#81]
Here is the log I haven't installed the plugin in the ETS2 game folder yet.

21:39:47: System.Exception: No joystick found
   at ETS2_Local_Radio_server.SimpleJoystick..ctor(String deviceName) in F:\Mods\ETS2\ETS2 Map Capture Tool\ets2-local-radio\server\ETS2 Local Radio desktop\Joystick.cs:line 75
   at ETS2_Local_Radio_server.Main.AttachJoystick() in F:\Mods\ETS2\ETS2 Map Capture Tool\ets2-local-radio\server\ETS2 Local Radio desktop\Main.cs:line 336
21:39:48: System.Exception: No joystick found
   at ETS2_Local_Radio_server.SimpleJoystick..ctor(String deviceName) in F:\Mods\ETS2\ETS2 Map Capture Tool\ets2-local-radio\server\ETS2 Local Radio desktop\Joystick.cs:line 75
   at ETS2_Local_Radio_server.Main.AttachJoystick() in F:\Mods\ETS2\ETS2 Map Capture Tool\ets2-local-radio\server\ETS2 Local Radio desktop\Main.cs:line 336

**Comment by Rayzer78** [comment]
I have finally have got the mod working   again but it appears my PC is still not working correctly. Thanks for your time
